# Generated by Django 4.1.4 on 2022-12-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="essay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="题目")),
                ("answer", models.TextField(verbose_name="答案")),
                ("analysis", models.TextField(verbose_name="解析")),
                ("tags", models.CharField(max_length=20, verbose_name="标签")),
            ],
        ),
    ]
