# Generated by Django 4.1.4 on 2022-12-13 02:22

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_bank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="essay",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="upimg/%Y/%m/%d/", verbose_name="文章图片"
            ),
        ),
        migrations.AlterField(
            model_name="essay",
            name="answer",
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name="答案"),
        ),
    ]
