# Generated by Django 4.1.4 on 2022-12-13 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question_bank", "0002_essay_img_alter_essay_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="文章标签")),
            ],
            options={"verbose_name": "文章标签", "verbose_name_plural": "文章标签",},
        ),
        migrations.AlterField(
            model_name="essay",
            name="tags",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="question_bank.tag",
                verbose_name="标签",
            ),
        ),
    ]
